kind: pipeline
name: default

.node-image: &node-image
  image: node:10-alpine

.environment-variables: &environment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME:
    from_secret: BUCKET_NAME
  BUCKET_OBJECT:
    from_secret: BUCKET_OBJECT

steps:
  - name: deploy
    <<: *node-image
    environment:
      <<: *environment-variables
      WORKSPACE: feature
    commands:
      - ls -la
