kind: pipeline
name: default

.node-image: &node-image
  image: node:10-alpine

.environment-variables: &environment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME:
    from_secret: BUCKET_NAME
  BUCKET_OBJECT:
    from_secret: BUCKET_OBJECT

steps:
  - name: deploy
    <<: *node-image
    environment:
      <<: *environment-variables
      WORKSPACE: feature
    commands:
      - apk add --no-cache \
        rsync \
        python \
        py-pip && \
        pip install awscli --upgrade --user && \
        mv /root/.local/bin/* /usr/local/bin && \
        apk -v --purge del py-pip && \
        mkdir -p dist && \
        zip -r dist/rumours-lambda.zip ./ \
        -x \"*.git*\" \
        -x \"*node_modules*\" \
        -x \"*test*\" \
        -x \"*.nyc_output*\" && \
        aws s3 sync dist/ s3://$BUCKET_NAME
