kind: pipeline
name: default

.deployment-variables: &deployment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1

steps:
- name: build
  image: python:2.7-alpine
  commands:
    - apk update && apk add zip
    - zip -r -9 rumours-lambda.zip ./ -x \"*.git*\" -x \"*node_modules*\" -x \"*test*\" -x \"*.nyc_output*\"

- name: s3-publish
  image: plugins/s3
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    bucket: rumours.football
    region: eu-west-1
    target: /
    source: rumours-lambda.zip
  # when:
  #   branch:
  #     include:
  #       - master
    event:
      - push

- name: deploy-lambda
  image: quay.io/honestbee/awscli:1.11.55
  <<: *deployment-variables
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - mkdir ~/.aws
    - echo -e "[default]\nAWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID\nAWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
    - aws lambda update-function-code --s3-bucket rumours.football --function-name rumours --s3-key rumours-lambda.zip --region eu-west-1
  # when:
  #   branch:
  #     include:
  #       - master
    event:
      - push
