kind: pipeline
name: default

steps:
- name: build
  image: python:2.7-alpine
  commands:
    - apk update && apk add zip
    - zip -r rumours-lambda.zip *
  # volumes:
  #   - name: code
  #     path: /opt/code

# - name: s3-publish
#   image: plugins/s3
#   volumes:
#     - name: code
#       path: /opt/code
#   settings:
#     access_key:
#       from_secret: AWS_ACCESS_KEY_ID
#     secret_key:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     bucket: rumours.football
#     region: eu-west-1
#     target: rumours-lambda.zip
#     source: /opt/code/rumours-lambda.zip

- name: deploy-lambda
  image: mesosphere/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: eu-west-1
    commands:
      - aws lambda update-function-code --function-name rumours -- Zip-file fileb://./rumours-handler.zip

volumes:
  - name: code
    temp: {}
