pipeline:
  build:
    image: python:2.7-alpine
    commands:
      - apk update && apk add zip
      - pip install -r requirements.txt -t .
      - zip -r -9 rumours-lambda.zip *

  s3-publish:
    image: plugins/s3
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      bucket:
        from_secret: BUCKET_NAME
      region: eu-west-1
      target:
        from_secret: BUCKET_OBJECT
      source: ./dist/rumours-lambda.zip

  deploy-lambda:
      image: omerxx/drone-lambda-plugin
      pull: true
      function_name: rumours
      s3_bucket:
        from_secret: BUCKET_NAME
      file_name:
        from_secret: BUCKET_OBJECT
