kind: pipeline
name: default

.environment-variables: &environment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME:
    from_secret: BUCKET_NAME
  BUCKET_OBJECT:
    from_secret: BUCKET_OBJECT

  s3-publish:
    image: plugins/s3
    acl: private
    region: eu-west-1
    bucket:
      from_secret: BUCKET_NAME
    target:
      from_secret: BUCKET_OBJECT
    source: dist/rumours-lambda.zip
