kind: pipeline
name: default

steps:
- name: build
  image: python:2.7-alpine
  commands:
    - apk update && apk add zip
    - zip -r rumours-lambda.zip *

- name: deploy-lambda
  image: mesosphere/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: eu-west-1
  commands:
    - aws lambda update-function-code --function-name rumours -- Zip-file fileb://./rumours-handler.zip

volumes:
  - name: code
    temp: {}
