kind: pipeline
name: default

.environment-variables: &environment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME:
    from_secret: BUCKET_NAME
  BUCKET_OBJECT:
    from_secret: BUCKET_OBJECT

steps:
- name: s3-publish
  image: plugins/s3
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    bucket:
      from_secret: BUCKET_NAME
    region: eu-west-1
    target:
      from_secret: BUCKET_OBJECT
    source: dist/rumours-lambda.zip
