kind: pipeline
name: default

.environment-variables: &environment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1
  BUCKET_NAME:
    from_secret: BUCKET_NAME
  BUCKET_OBJECT:
    from_secret: BUCKET_OBJECT

steps:
- name: code-zip
  image: alpine:latest
  volumes:
    - name: code
      path: /opt/code
  commands:
    - apk-add zip && \
      mkdir -p /opt/code && \
      zip -r /opt/code/rumours-lambda.zip ./ \
      -x \"*.git*\" \
      -x \"*node_modules*\" \
      -x \"*test*\" \
      -x \"*.nyc_output*\"

- name: s3-publish
  image: plugins/s3
  volumes:
    - name: code
      path: /opt/code
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    bucket:
      from_secret: BUCKET_NAME
    region: eu-west-1
    target:
      from_secret: BUCKET_OBJECT
    source: /opt/code/rumours-lambda.zip

volumes:
  - name: code
    temp: {}
